// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var log, stringBuilder,
      _this = this;
    stringBuilder = [];
    log = [];
    $('body').append('<ul id="string-list"></ul>');
    $('body').append('<input type="text" id="current-string">');
    return $(document).on('keypress', function(e) {
      if (e.keyCode === 8) {
        return stringBuilder.splice(stringBuilder.length, -1);
      } else if (e.keyCode === 13) {
        $('#current-string').val('');
        $('#string-list').append("<li>" + (stringBuilder.join('')) + "</li>");
        log.push(stringBuilder);
        return stringBuilder = [];
      } else if (e.keyCode >= 48 || e.keyCode <= 90) {
        stringBuilder.push(String.fromCharCode(e.keyCode));
        return $('#current-string').val(stringBuilder.join(''));
      }
    });
  });

}).call(this);
