// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var log, stringBuilder, updateInput,
      _this = this;
    stringBuilder = [];
    log = [];
    updateInput = function(val) {
      return $('#current-string').val(val);
    };
    $('body').append('<ul id="string-list"></ul>');
    $('body').append('<input type="text" id="current-string">');
    $(document).on('keydown', function(e) {
      if (e.keyCode === 8) {
        stringBuilder.pop();
        return updateInput(stringBuilder.join(''));
      } else if (e.keyCode === 13) {
        updateInput('');
        $('#string-list').append("<li>" + (stringBuilder.join('')) + "</li>");
        log.push(stringBuilder);
        return stringBuilder = [];
      }
    });
    return $(document).on('keypress', function(e) {
      if (e.keyCode >= 48 || e.keyCode <= 90) {
        stringBuilder.push(String.fromCharCode(e.keyCode));
        return updateInput(stringBuilder.join(''));
      }
    });
  });

}).call(this);
